<?
// Added this comment
$GLOBALS['emailcategories'] = Array (
    'AFF_EMAIL_SIGNUP',
    'AFF_EMAIL_FORGOTPAS1',
    'AFF_EMAIL_FORGOTPAS2',
    'AFF_EMAIL_NTF_SIGNUP',
    'AFF_EMAIL_NTF_SALE',
    'AFF_EMAIL_NOTIFY_RC',
    'AFF_EMAIL_DAILY_REP',
    'AFF_EMAIL_AF_NTF_SGN',
    'AFF_EMAIL_AF_NTF_SLE',
    'AFF_EMAIL_AF_DL_REP',
    'AFF_EMAIL_AFF_CAMP_A',
    'AFF_EMAIL_CONTACT_US'
);

?>
